# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('aplicacion', models.CharField(max_length=255)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
