# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lenguaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenguaje',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
