# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lenguaje', '0002_auto_20180503_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenguaje',
            name='puntaje',
            field=models.IntegerField(default=10),
        ),
    ]
