# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lenguaje', '0003_auto_20180507_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenguaje',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
